# Generated by Django 4.0.4 on 2022-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='language name')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='language code')),
                ('blurb', models.TextField(default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
