# Generated by Django 4.0.4 on 2022-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='type',
            field=models.CharField(choices=[('natlang', 'Natlang'), ('conlang', 'Conlang'), ('other', 'Other')], default='other', max_length=7),
        ),
    ]
