# Generated by Django 4.0.4 on 2022-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='forms',
            new_name='extra_forms',
        ),
        migrations.AddField(
            model_name='variant',
            name='form',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='gloss',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
