# Generated by Django 3.2.9 on 2022-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0001_squashed_0008_alter_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.TextField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
