# Generated by Django 3.2.9 on 2021-11-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0002_auto_20211027_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='language name')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='language code')),
                ('hasgrammar', models.BooleanField(default=False)),
                ('blurb', models.TextField(default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=50)),
                ('homonym', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('r', 'Root'), ('br', 'Bound Root'), ('s', 'Stem'), ('pf', 'Prefix'), ('if', 'Infix'), ('sf', 'Suffix'), ('cf', 'Circumfix'), ('pc', 'Proclitic'), ('ec', 'Enclitic')], default='s', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('etymology', models.TextField(blank=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonlinguistics.language', verbose_name='language')),
            ],
            options={
                'ordering': ['lemma', 'homonym'],
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(max_length=20)),
                ('defin', models.TextField(blank=True, verbose_name='definition')),
                ('pos', models.CharField(choices=[('aff', 'Affix'), ('adj', 'Adjective'), ('adp', 'Adposition'), ('adv', 'Adverb'), ('conj', 'Conjunction'), ('det', 'Determiner'), ('intj', 'Interjection'), ('n', 'Noun'), ('num', 'Numeral'), ('part', 'Particle'), ('pron', 'Pronoun'), ('pn', 'Proper Noun'), ('unk', 'Unknown'), ('v', 'Verb')], default='unk', max_length=4, verbose_name='part of speech')),
                ('grammclass', models.CharField(blank=True, max_length=20, verbose_name='class')),
                ('notes', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonlinguistics.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('lang', 'lemma', 'homonym'), name='unique-homonym'),
        ),
    ]
