# Generated by Django 3.2.9 on 2022-02-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0003_alter_reference_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='link',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
