# Generated by Django 3.2.9 on 2021-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0004_auto_20211122_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
