# Generated by Django 3.2.9 on 2022-02-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0004_alter_reference_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['lemma', 'id']},
        ),
    ]
