# Generated by Django 3.2.9 on 2022-01-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0006_auto_20220108_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent',
        ),
        migrations.AlterField(
            model_name='article',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dragonlinguistics.folder'),
        ),
    ]
