# Generated by Django 4.0.4 on 2022-05-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0006_fix_word'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='article',
            name='number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
