# Generated by Django 4.0.4 on 2022-05-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0007_alter_article_options_article_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.TextField(blank=True, verbose_name='lexical classes')),
                ('order', models.TextField(blank=True, verbose_name='alphabetical order')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dragonlinguistics.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexclass', models.CharField(max_length=20, verbose_name='class')),
                ('forms', models.TextField(blank=True)),
                ('definition', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('derivatives', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='word',
            name='notes',
        ),
        migrations.AddField(
            model_name='word',
            name='descendents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='isunattested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('r', 'Root'), ('s', 'Stem'), ('pf', 'Prefix'), ('if', 'Infix'), ('sf', 'Suffix'), ('cf', 'Circumfix'), ('pc', 'Proclitic'), ('ec', 'Enclitic')], default='s', max_length=2),
        ),
        migrations.DeleteModel(
            name='Sense',
        ),
        migrations.AddField(
            model_name='variant',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', related_query_name='variant', to='dragonlinguistics.word'),
        ),
        migrations.AddField(
            model_name='word',
            name='dictionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', related_query_name='word', to='dragonlinguistics.dictionary'),
        ),
    ]
