# Generated by Django 3.2.9 on 2022-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonlinguistics', '0007_auto_20220115_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.TextField(blank=True),
        ),
    ]
