# Generated by Django 4.0.4 on 2022-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['author', 'year', 'id'],
            },
        ),
    ]
