# Generated by Django 4.0.4 on 2022-07-16 07:26

from django.db import migrations, models
import django.db.models.deletion

def migrate_authors(apps, schema_editor):
    Author = apps.get_model('references', 'Author')
    Reference = apps.get_model('references', 'Reference')
    for reference in Reference.objects.all():
        surname, forenames = [*reference._author.split(','), ''][:2]
        reference.author, _ = Author.objects.get_or_create(forenames=forenames, surname=surname)
        reference.save()


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forenames', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('alphabetise', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['alphabetise'],
            },
        ),
        migrations.RenameField(
            model_name='reference',
            old_name='author',
            new_name='_author',
        ),
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.author', null=True),
        ),
        migrations.RunPython(migrate_authors),
        migrations.RemoveField(
            model_name='reference',
            name='_author',
        ),
    ]
